### ISSUE TITLE
Frontfest logo 

### ISSUE THREAD

**Issue by Xaviju** [frontfest/design#1]
**Necesitamos un logo para el frontfest**. Este logo debería ir acompañado o encajar bien con una imagen visual general que deberíamos aplicar a la web así como cualquier tipo de branding.

De momento lo único que hemos definido común identitario es que se trata de un evento de front que engloba todos los apartados de desarrollo de interfaz (HTML, CSS, JS) y la interacción del front con otros perfiles del desarrollo web.

Bocetos e ideas genéricas son bienvenidas para que entre todos las mejoremos.

Ejemplos:
- Diseño de la web de postCSS: https://github.com/postcss/postcss.org/issues/4
- Diseño del logo de opensourcedesign: https://github.com/opensourcedesign/opensourcedesign.github.io/issues/18

**Comment by NoemiMS** [comment]
Aquí os dejo algunas pruebas que he hecho :see_no_evil::see_no_evil::see_no_evil:

![logo-geo01](https://cloud.githubusercontent.com/assets/9264868/16491778/9462b958-3edf-11e6-9c2e-b840486ebf93.png)
![logo-geo02](https://cloud.githubusercontent.com/assets/9264868/16491780/9a11da32-3edf-11e6-8502-4d3f4ccd8ab6.png)

Estos dos son simples y meh! pero por probar... Ahora vienen los que más me gustan

![logo-fest02](https://cloud.githubusercontent.com/assets/9264868/16491806/aa777666-3edf-11e6-9502-28ea5d342e16.png)
![logo-fest01](https://cloud.githubusercontent.com/assets/9264868/16491813/ae082096-3edf-11e6-8779-ac1b7392881c.png)

La tipo del segundo no me convence mucho, pero es la única que he encontrado rápidamente en fonts con el tag "rock" :joy:

Sed bueninos :metal::pray:

**Comment by arcxyz** [comment]
Uno rápido 🎉 🎉 :

![frontfest 1 white](https://cloud.githubusercontent.com/assets/185002/16527290/3b902fc2-3fb6-11e6-8e92-1ebeb9235bd4.png)

![frontfest 1 black](https://cloud.githubusercontent.com/assets/185002/16527295/40025d46-3fb6-11e6-99db-bc4983c8a9f8.png)

Tengo algunas ideas más y otras variaciones de este dibujadas en el cuaderno. Cuando vaya teniendo tiempo los voy vectorizando 😉

**Comment by cristinafsanz** [comment]
Otras propuestas para el logo, intentando acercarme a la temática de festival :) Creo que las fuentes que cogí no son open source, que Inkscape muestra las que tiene el equipo, pero bueno, se podrían mirar fuentes open source similares.

![frontfest_logo](https://cloud.githubusercontent.com/assets/7030244/16708308/5cb412a2-45ee-11e6-8903-300a81d05be7.png)

![fronfest_ravie](https://cloud.githubusercontent.com/assets/7030244/16765803/9874bd60-4836-11e6-838e-f64091adfb40.png)

![fronfest_ravie_shadow](https://cloud.githubusercontent.com/assets/7030244/16800481/d9663672-48f5-11e6-93b7-9fbe8c64ddae.png)

**Comment by Xaviju** [comment]
Basándome en el hecho de que casi todos hemos tirado por los `</>` he hecho una propuesto un poco más suave. A ver qué os parece:

![logo_front_fest](https://cloud.githubusercontent.com/assets/1343702/16948155/542d1b5c-4db3-11e6-9032-64f2b39bd721.png)

Me pregunto si se nos ocurre algún modo de innovar en el símbolo.

**Comment by v4n3ss4ms** [comment]
Aviso, no tengo ni idea de diseño, así que me muevo por "me gusta" / "no me gusta" y matices de calado similar.
Por un lado pensaba que queríamos un logo más "festivalero" si es que eso tiene sentido para alguien.
Por otro lado lo de las efes así revueltas mola, pero elegiría algo menos colorido.

Por ahora me molan:
- el 3º de Noe porque es el más macarra
- el 2º de Arcxyz porque es el más serio
- el logo de Xaviju por el revoltijo de efes

Sí, lo sé, seguramente todo lo que haya dicho sea un desvarío.
Lo siento, no volverá a pasar :D

**Comment by Xaviju** [comment]
Yo creo que lo de festivalero era una idea que en verano queda muy on-topic aunque no sé si en Febrero puede ser menos obvio. Voy a echar un ojo a festivales musicotronicos para inspirarme pero me apetece también abrir la mente a otras propuestas menos temáticas.

**Comment by v4n3ss4ms** [comment]
¡Ojo! Que yo lo digo porque nos llamamos "fest" jejejejeje.

**Comment by Xaviju** [comment]
Yo he seguido dándole vueltas a la idea de F == </>
Nueva propuesta!

![proposal4](https://cloud.githubusercontent.com/assets/1343702/18512841/2c2a3c3e-7a8b-11e6-89c0-4283c86691f7.png)

Sigo sin tener muy claros los colores, pero la cosa va por ahí (contraste)

**Comment by fergpichel** [comment]
Esta última versión me mola. El logo es limpio y no veo necesidad de complicarlo más. El texto no acabo de ver el "Fest" en modo reflejo, prefiero que sea más legible. Quizá "Fest" en bold y con otra tipo ...
Probaré con algunas a ver si queda bien.

**Comment by IgnaciodeNuevo** [comment]
El logo de @xaviju de momento es mi favorito salvo que haría dos cambios principales, el color (la parte amarilla) no es muy visible para algunos ususarios (hemos de pensar en accesibilidad ya que estamos) y el fest dado la vuelta lo pondría quizá a la derecha seguido a Front o si es debajo ok pero en posición normal y como dice @fergpichel en otro peso, quizá en bold Front que es lo importante

**Comment by cristinafsanz** [comment]
Yo también me quedaría con esta última versión de @Xaviju con el cambio lo que comentan @fergpichel e @IgnaciodeNuevo, el texto FEST en posición normal. El resto lo veo bien aunque si por accesibilidad conviene otro color, por mí bien.

**Comment by arcxyz** [comment]
Yo también me quedo con el último de @Xaviju y lo mismo, cambiaría el reflejo.
Por otro lado, como sugerencia para los colores podemos jugar con los típicos que se usan para  HTML (naranja), CSS (azul) y JS (Amarillo):

![image](https://cloud.githubusercontent.com/assets/185002/18518821/d8ccb83e-7aa1-11e6-94c3-7e22a67334f8.png)

**Comment by v4n3ss4ms** [comment]
El logo de @Xaviju Xaviju me mola un montón, pero el Fest lo pondría del derecho y sólo cambiaría el color de la F amarilla por lo que comentáis sobre accesibilidad, el resto lo dejaría como está, eso sí personalmente huiría de los colores de los logos de html, css y js porque están muy usados.

**Comment by Xaviju** [comment]
Aquí tenéis el SVG por si queréis iterar sobre él. La fuente es [Josefin Sans](https://fonts.google.com/specimen/Josefin+Sans)

https://www.dropbox.com/s/j6taksnnphe2ldg/proposal4.svg?dl=0

**Comment by cocotime** [comment]
Chicos os paso unas propuestas que me ha hecho una amiga =)

![propuestas logos 1](https://cloud.githubusercontent.com/assets/5970959/18579102/c4f4eae0-7bf3-11e6-821a-09a322089c11.jpg)
![propuestas logos 2](https://cloud.githubusercontent.com/assets/5970959/18579103/c4f64bec-7bf3-11e6-8bce-9c4155dfa712.jpg)

**Comment by v4n3ss4ms** [comment]
@cocotime me mola el amarillo/gris de la derecha

**Comment by cristinafsanz** [comment]
Aquí va la primera iteración a partir del SVG de @Xaviju. He probado con distintos colores y he cambiado la fuente a bold a ver qué os parece:

![frontfest6](https://cloud.githubusercontent.com/assets/7030244/18806974/671bdf88-823c-11e6-8eba-7651b7b5c7e5.png)
![frontfest_logo_iteration4](https://cloud.githubusercontent.com/assets/7030244/18999260/f59607d4-873c-11e6-9893-2512a3f14c35.png)
![frontfest_logo_iteration5](https://cloud.githubusercontent.com/assets/7030244/18999280/12e2ed66-873d-11e6-9968-53e455856723.png)
![frontfest_logo_iteration6](https://cloud.githubusercontent.com/assets/7030244/18999625/e0cd58aa-873e-11e6-9c30-bfbd409a5c13.png)

He subido uno de los SVG a Google Drive por si queréis iterar a partir de él: https://drive.google.com/drive/folders/0B046anz_6sKmOV8zdVRRSl9GMFU

**Comment by Xaviju** [comment]
Ahí va otra vuelta de tuerca al logo a ver qué os parece.

![proposal5](https://cloud.githubusercontent.com/assets/1343702/18878466/f04f65e0-84d0-11e6-9e8b-6708c6608580.png)

**Comment by Xaviju** [comment]
Y al de @cocotime le he dado una vuelta también haciéndolo más parecido al CSS3/HTML5. Lo he hecho en morado para alejarnos un poco de los colores habituales pero puede variar.

Nota: la typo es una versión extendida de la typo oficial de ese logo en su versión CSS3

![proposal6](https://cloud.githubusercontent.com/assets/1343702/18879240/d530262a-84d3-11e6-903c-005f562ae999.png)

(Espero que no nos denuncien por plagio los amigos de Fear Factory)

**Comment by IgnaciodeNuevo** [comment]
Me quedo con los de @cristinafsanz muy sencillos, fáciles de ver y elegantes, lo único (bajo mi forma de ver, miraría colores)

**Comment by NoemiMS** [comment]
Me encanta el logo moradito último de @Xaviju . Todo mi amor para ese logo. Lo único que cambiaría es la tipo, que es muy rara, jeje.

En segundo lugar, las iteraciones de @cristinafsanz me gustan también, la primera en negro-turquesa me gusta mucho, soy muy fan de esos colores y su combinación. 

La segunda iteración de @Xaviju sobre su propio logo no me convence, no sé por qué me recuerda a algo de bricks para niños. Muahaha.

(Dejo aquí mi opinión para que conste, no sé si podré asistir a la siguiente reu).

**Comment by cocotime** [comment]
Con etiqueta de cierre 

![ff-logo-new](https://cloud.githubusercontent.com/assets/5970959/19047518/6ca3fa0e-89a2-11e6-9677-b9757b9e4a32.jpg)

**Comment by Xaviju** [comment]
![proposal7](https://cloud.githubusercontent.com/assets/1343702/19082908/60266406-8a60-11e6-9e4f-e6a55dcc41c1.png)

**Comment by v4n3ss4ms** [comment]
Yo es que con mi visión obtusa no entiendo el logo de las 2 efes. Es decir me cuesta asociarlo con un evento de programación, creo que está chulo pero no lo asocio :(
Eso sí, sobre fondo negro queda guay.

**Comment by Xaviju** [comment]
Bueno quizá no se ha entendido bien o yo me he empecinado en ello demasiado. En realidad no son las dos efes sino **una mezcla entre < / > y las dos efes**. 
Cuado estoy pensando el logo estoy pensando en varias cosas:
- El nombre del evento
- Símbolos de HTML, CSS, JS como {} ; () </>
- Los colores de los logos "oficiales"
- Otros logos de eventos
- Otros logos de proyectos

De todas estas estoy mezclando algunas y me sale este logo. LO que he hecho para inspirarme es echarle un ojo a los logos de los principales proyectos en NPM y en los logos de eventos tecnológicos.

Yo no soy diseñador, así que lo que hago es copiar estilos, no inventarlos, y el estilo de este último se parece a 10000 logos que han salido en el último año así que para mí tenía sentido.

De todas formas, también, además de crear un logo vosotras, también podéis poner aquí cualquier logo que econtréis relacionado con eventos, proyectos, empresas, etc. que os parezcan que podrían servir como inspiración para crear uno. ¿Que logo representa mejor la programación de UI, incluyendo estructura, estilo visual, componentización, animación, interacción...?

**Comment by luisCalvo** [comment]
Enhorabuena Xaviju, parece que has dado en el clavo con el logo. De momento, ¡¡¡unanimidad total!!!

**Comment by Xaviju** [comment]
El logo definitivo en SVG (Inkscape) aquí -> https://media.taiga.io/attachments/5/8/f/9/8d3e7981f07c0a2d3db96be12e76d16063878bd30789f263559b5af872b9/logo.svg
