### ISSUE TITLE
Web template

### ISSUE THREAD

**Issue by Xaviju** [frontfest/design#2]
Abro esta issue para que compartamos los web templates que encontremos.
La idea es que el template del sitio sea estático y con el mínimo posible de modificaciones sea adaptable a un sitio web para eventos.

Debería contener al menos una página o sección para:
- Presentación
- Agenda 
- Ponentes
- Ubicación del evento
- Compra de entradas
- ...

Esta semana podemos compartir aquellos templates que nos parezcan interesantes y haremos la votación la semana que viene de manera que para la próxima reunión ya tengamos un template ganador subido.

**Comment by juanfran** [comment]
y si es Creative Commons mejor

**Comment by v4n3ss4ms** [comment]
He mirado templates sencillos, aquí mi selección:
- De html5 up! (100% Free under the Creative Commons) me gustan estas dos: 
  - https://html5up.net/helios
  - https://html5up.net/hyperspace
- De styleshout (Creative Commons Attribution 3.0 License):
  - Con cuenta atrás http://www.styleshout.com/demo/?theme=khronos

**Comment by IgnaciodeNuevo** [comment]
A mi por gustarme me gusta Hyperspace de las que ha puesto @v4n3ss4ms 
- Y https://html5up.net/solid-state

**Comment by juanfran** [comment]
https://freehtml5.co/preview/?item=stamina-free-html5-bootstrap-template-for-fitness-websites

**Comment by Xaviju** [comment]
Me gusta mucho este también: http://www.styleshout.com/demo/?theme=elevate

Imaginad que (de arriba a abajo):
- la parte de **Features You'll Love** (amarillo) son el título la hora y el resto la charla más abstract
- más abajo, reducimos el alto y tenemos en cada uno a un speaker
- En las estadísticas ponemos cosas de coña random, como litros de cafeína, número de diapositivas, etc.
- En plans and pricing, comprar entrada
- Justo abajo, ponemos una sección de sponsors (copypaste de la de estadísticas)
- En **Hear What Our Customers Say.** lo conectamos con el tuiter
- Por último, en **Download** ponemos un mapa del campus de fondo y la dirección.

**Comment by NoemiMS** [comment]
De las que se han compartido, tenía fichadas la Hyperspace de @v4n3ss4ms y la que ha puesto @IgnaciodeNuevo (sobre todo porque las líneas oblicuas me recordaban a las lineas del logo).

**Evento**\- [http://shapebootstrap.net/demo/html/evento/](http://shapebootstrap.net/demo/html/evento/)
Es la que os compartí durante la última reunión. Las secciones que hay, las mantendría adaptadas a nuestro contenido. Además añadiría una página de "Hazte patrocinador" si fuera necesario (algo parecido a lo que tienen en el techfecth).

**EventZ** [http://codeboxr.com/themedemo/#eventz](http://codeboxr.com/themedemo/#eventz)
Esta plantilla también está orientada a un evento, incluye sección speakers, schedule, incluso si llegáramos a hablar con algún hotel (os explico en la siguiente reunión) tendríamos la sección :)

**Finiti** [http://demo.deviserweb.com/finiti/image-bg/style-2/index.html](http://demo.deviserweb.com/finiti/image-bg/style-2/index.html)
Otra plantilla para eventos.

**NRGEvent** [http://demo.nrgthemes.com/projects/nrgeventhtml/festival_header_3.html#/speakers](http://demo.nrgthemes.com/projects/nrgeventhtml/festival_header_3.html#/speakers)
De esta me gusta especialmente el diseño, porque las secciones son iguales que en otras para eventos (me centré en eso en la búsqueda). Sobre todo destaco la forma de mostrar a los speakers.

**Eventr** [http://themecube.net/eventr/](http://themecube.net/eventr/)
La última que os añado, es una plantilla clásica para un evento, parecida a la que ha propuesto @Xaviju
